name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  config: Release

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20


    steps:
    - uses: actions/checkout@v2

    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Test
      run: dotnet test src/JasperFx.Core/JasperFx.Core.csproj
